play/apps/core/urls.py
from django.shortcuts import redirect
from django.urls import path

from apps.core.views import game, home, profile, profiles, snake, stats
from util.routing import method_dispatch as route


urlpatterns = [
    path(
        "settings/",
        route(GET=profile.edit, PUT=profile.update, DELETE=profile.delete),
        name="settings",
    ),
    path("u/by-games-snake/<game_snake_id>", route(GET=profiles.show_by_game_snake)),
    path("u/<username>/", route(GET=profiles.show), name="u"),
    path("", route(GET=home.index), name="home"),
    path("s/new/", route(GET=snake.new, POST=snake.create), name="new_snake"),
    path("s/<snake_id>/", route(GET=snake.show, DELETE=snake.delete), name="snake"),
    path(
        "s/<snake_id>/edit/", route(GET=snake.edit, PUT=snake.update), name="snake_edit"
    ),
    path("g/new/", route(GET=game.new, POST=game.create), name="new_game"),
    path("g/snake-autocomplete/", route(GET=game.snake_autocomplete)),
    path("g/snake-info/", route(GET=game.snake_info)),
    path("g/random-public-snake/", route(GET=game.random_public_snake)),
    path("g/<engine_id>/", route(GET=game.show), name="game"),
    path("g/<engine_id>/gif", route(GET=game.show_gif), name="game_gif"),
    path("stats/", route(GET=stats.show), name="stats"),
    # Old redirects
    path("games/new/", lambda req: redirect("new_game")),
    path("games/<engine_id>/", lambda req, engine_id: redirect("game", engine_id)),
]

play/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from apps.authentication.views import send_to_login

admin.site.login = send_to_login

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.authentication.urls")),
    path("", include("apps.core.urls")),
    path("", include("apps.leaderboard.urls")),
    path("", include("apps.pages.urls")),
    path("", include("apps.tournament.urls")),
    path("", include("apps.ops.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns


handler400 = "apps.pages.views.error400"
handler403 = "apps.pages.views.error403"
handler404 = "apps.pages.views.error404"
handler500 = "apps.pages.views.error500"

play/apps/core/models/game.py
from django.db import models, transaction

from apps.core import engine
from apps.core.models import Snake
from util.fields import ShortUUIDField
from util.models import BaseModel


class GameQuerySet(models.QuerySet):
    def watchable(self):
        return self.filter(
            status__in=(
                Game.Status.CREATED,
                Game.Status.RUNNING,
                Game.Status.STOPPED,
                Game.Status.COMPLETE,
            )
        ).exclude(engine_url__icontains="engine.internal.battlesnake.io")


class Game(BaseModel):
    """
    Game tracks a game started on the engine locally in the snake database. You
    can initialize a game through this model and call run() to start the game.
    Then, you can also call update_from_engine() at any point to refresh the
    game state from the engine onto this model.

    Creating a game looks like:

        game = Game(...) # instance created with config, ready to go
        game.create()    # game snakes created, and any other future pre-game things
        game.run()       # (OPTIONAL) sent to engine, and now it's running!
    """

    class NotCreatedError(Exception):
        pass

    class Status:
        PENDING = "pending"
        CREATED = "created"
        RUNNING = "running"
        ERROR = "error"
        STOPPED = "stopped"
        COMPLETE = "complete"

    id = ShortUUIDField(prefix="gam", max_length=128, primary_key=True)
    engine_id = models.CharField(null=True, max_length=128)
    status = models.CharField(default=Status.PENDING, max_length=30)
    turn = models.IntegerField(default=0)
    width = models.IntegerField()
    height = models.IntegerField()
    max_turns_to_next_food_spawn = models.IntegerField(default=15)
    snakes = models.ManyToManyField(Snake)
    engine_url = models.CharField(null=True, max_length=128)

    objects = GameQuerySet.as_manager()

    def config(self):
        """ Fetch the engine configuration. """
        config = {
            "width": self.width,
            "height": self.height,
            "maxTurnsToNextFoodSpawn": self.max_turns_to_next_food_spawn,
            "food": self.snakes.count(),
            "snakeTimeout": 250,
            "snakes": [
                {
                    "name": gs.name if len(gs.name) > 0 else gs.snake.public_name,
                    "url": gs.snake.url,
                    "id": gs.id,
                }
                for gs in self.gamesnake_set.all()
            ],
        }
        return config

    @transaction.atomic
    def create(self):
        """ Call the engine to create the game. Returns the game id. """
        config = self.config()
        self.engine_id = engine.create(config, self.engine_url)
        self.status = Game.Status.CREATED
        self.save()
        return self.engine_id

    def run(self):
        """ Call the engine to start the game. Returns the game id. """
        engine.run(self.engine_id, self.engine_url)
        return self.engine_id

    def engine_status(self):
        return engine.status(self.engine_id, self.engine_url)

    def update_from_engine(self):
        """ Update the status and snake statuses from the engine. """
        if self.engine_id is None:
            raise self.NotCreatedError("Game is not created")
        with transaction.atomic():
            status = engine.status(self.engine_id, self.engine_url)
            self.status = status["status"]
            self.turn = status["turn"]

            for game_snake in self.gamesnake_set.all():
                snake_status = status["snakes"][game_snake.id]
                game_snake.death = snake_status["death"]
                game_snake.save()

            self.save()
            return status

    @property
    def game_snakes(self):
        return self.gamesnake_set.all()

    def alive_game_snakes(self):
        return self.game_snakes.filter(death="pending")

    def winner(self):
        if self.status == self.Status.COMPLETE:
            living_snakes = self.alive_game_snakes()
            if living_snakes.count() == 1:
                return living_snakes.first()


class GameSnake(BaseModel):
    id = ShortUUIDField(prefix="gs", max_length=128, primary_key=True)
    snake = models.ForeignKey(Snake, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    death = models.CharField(default="pending", max_length=128)
    turns = models.IntegerField(default=0)
    name = models.CharField(default="", max_length=128)

play/apps/core/forms/games.py
from django import forms
from django.db.models import Q

from apps.core.models import Snake, Game, GameSnake


class GameForm(forms.Form):
    """
        GameForm initializes a game and posts this to the engine to start the game.
    """

    board_size = forms.ChoiceField(
        choices=[
            ("small", "Small - 7x7"),
            ("medium", "Medium - 11x11"),
            ("large", "Large - 19x19"),
            ("custom", "Custom"),
        ],
        required=True,
        initial="medium",
    )
    width = forms.IntegerField(initial=11, required=False)
    height = forms.IntegerField(initial=11, required=False)
    snakes = forms.CharField(widget=forms.HiddenInput())
    engine_url = forms.CharField(required=False)

    def save(self, user):
        data = self.cleaned_data
        width = data["width"]
        height = data["height"]
        if data["board_size"] == "small":
            width = 7
            height = 7
        elif data["board_size"] == "medium":
            width = 11
            height = 11
        elif data["board_size"] == "large":
            width = 19
            height = 19

        game = Game.objects.create(
            width=width,
            height=height,
            max_turns_to_next_food_spawn=12,
            engine_url=data["engine_url"],
        )
        snake_ids = self.cleaned_data["snakes"].split(",")
        snakes = Snake.objects.filter(Q(id__in=snake_ids)).can_view(user)
        for s in snakes.all():
            game.snakes.add(s)
        for snake_id in snake_ids:
            GameSnake.objects.create(snake=snakes.get(id=snake_id), game=game)
        game.save()
        return game

play/apps/core/views/game.py
from django.conf import settings
from django.db import transaction
from django.http import JsonResponse, Http404
from django.shortcuts import render, redirect

from apps.core.forms import GameForm
from apps.core.middleware import profile_required
from apps.core.models import Snake, Game
from apps.utils.helpers import generate_game_url, generate_exporter_url


@profile_required
def new(request):
    snake_ids = request.GET.get("snake-ids")
    form = GameForm(initial={"snakes": snake_ids, "engine_url": settings.ENGINE_URL})
    return render(request, "core/game/new.html", {"form": form})


@profile_required
@transaction.atomic
def create(request):
    form = GameForm(request.POST)
    if form.is_valid():
        game = form.save(request.user)
        game.create()
        game.gamesnake_set.add()
        game.run()
        return redirect(f"/g/{game.engine_id}")
    return render(request, "core/game/new.html", {"form": form}, status=400)


@profile_required
def snake_autocomplete(request):
    q = request.GET.get("q")
    snakes = (
        Snake.objects.can_view(request.user)
        .by_public_name(q)
        .prefetch_related("profile__user")
    )
    return JsonResponse(
        [{"value": snake.id, "text": snake.public_name} for snake in snakes], safe=False
    )


@profile_required
def snake_info(request):
    snake_ids = request.GET.get("snakes", "").split(",")
    snakes = Snake.objects.can_view(request.user).filter(id__in=snake_ids)
    return JsonResponse(
        [{"value": snake.id, "text": snake.public_name} for snake in snakes], safe=False
    )


@profile_required
def random_public_snake(request):
    count = int(request.GET.get("count", 1))
    snakes = Snake.objects.filter(is_public=True).order_by("?")[:count]
    return JsonResponse({"snakes": [snake.id for snake in snakes]})


@profile_required
def show(request, engine_id):
    try:
        game = Game.objects.get(engine_id=engine_id)
    except Game.DoesNotExist:
        raise Http404

    game_board_url = generate_game_url(game)

    if request.GET.get("enableLinks"):
        game_board_url = f"{game_board_url}&enableLinks=true"

    autoplay = request.GET.get("autoplay")
    if autoplay:
        game_board_url = f"{game_board_url}&autoplay=true"

    turn = request.GET.get("turn")
    if turn:
        game_board_url = f"{game_board_url}&turn={turn}"

    frame_rate = request.GET.get("frameRate")
    if frame_rate:
        game_board_url = f"{game_board_url}&frameRate={frame_rate}"

    return render(
        request,
        "core/game/show.html",
        {
            "url": game_board_url,
            "game_image": f"https://exporter.battlesnake.io/games/{game.engine_id}/gif",
            "game": game,
        },
    )


def show_gif(request, engine_id):
    try:
        game = Game.objects.get(engine_id=engine_id)
    except Game.DoesNotExist:
        raise Http404

    return redirect(generate_exporter_url(game.engine_id))

play/apps/core/views/game_test.py
import json

import mock
import pytest
from apps.core.factories import GameFactory, SnakeFactory
from apps.authentication.factories import UserFactory

user_factory = UserFactory()
snake_factory = SnakeFactory()
game_factory = GameFactory()


@pytest.fixture
def user(client):
    user = user_factory.login_as(client)
    return user


def test_new(user, client):
    response = client.get("/g/new/")
    assert response.status_code == 200


@mock.patch("apps.core.engine.run")
@mock.patch("apps.core.engine.create")
def test_create(create_mock, run_mock, user, client):
    create_mock.return_value = "a879f127-55c2-4b0c-99c9-bce09c9fc0cf"

    snake1 = snake_factory.basic(n=1, commit=True, profile=user.profile)
    snake2 = snake_factory.basic(n=1, commit=True, profile=user.profile)

    response = client.post(
        "/g/new/", {"board_size": "medium", "snakes": f"{snake1.id},{snake2.id}"}
    )
    assert response.status_code == 302
    assert len(create_mock.call_args_list) == 1
    assert len(run_mock.call_args_list) == 1


def test_show(user, client):
    engine_id = "a879f127-55c2-4b0c-99c9-bce09c9fc0cf"
    url = "game=" + engine_id

    game_factory.basic(engine_id=engine_id, commit=True)

    response = client.get(f"/g/{engine_id}/")
    assert response.status_code == 200
    assert url in response.content.decode("utf-8")


def test_snake_autocomplete(user, client):
    snake = snake_factory.basic(n=1, profile=user.profile)
    snake.name = "snaker"
    snake.save()
    response = client.get(f"/g/snake-autocomplete/?q={user.username}")
    j = json.loads(response.content)
    assert len(j) == 1
    assert j[0]["text"] == f"{user.username} / {snake.name}"
    response = client.get(f"/g/snake-autocomplete/?q={snake.name}")
    j = json.loads(response.content)
    assert len(j) == 1
    assert j[0]["text"] == f"{user.username} / {snake.name}"

play/apps/core/views/home.py
import random

from django.shortcuts import render

from apps.core.middleware import profile_required
from apps.core.models import Game
from apps.utils.helpers import generate_game_url


@profile_required
def index(request):
    games = list(
        Game.objects.filter(status=Game.Status.COMPLETE, turn__gte=100)
        .prefetch_related("gamesnake_set")
        .order_by("-created")[:40]
    )
    random.shuffle(games)
    games = [g for g in games if g.gamesnake_set.count() > 1]
    return render(
        request,
        "core/home.html",
        {
            "games": [
                {
                    "url": generate_game_url(g)
                    + "&autoplay=true&hideScoreboard=true&hideMediaControls=true&frameRate=6",
                    "engine_id": g.engine_id,
                }
                for g in games[:4]
            ]
        },
    )

play/apps/core/views/home_test.py
from apps.authentication.factories import UserFactory
from apps.core.factories import GameFactory, SnakeFactory
from apps.core.models import GameSnake

game_factory = GameFactory()
snake_factory = SnakeFactory()
user_factory = UserFactory()


def test_home(client):
    engine_id = "a879f127-55c2-4b0c-99c9-bce09c9fc0cf"
    url = "game=" + engine_id

    games = game_factory.basic(
        n=20, engine_id=engine_id, status="complete", turn=200, commit=True
    )
    game = games[0]
    profile = user_factory.basic(commit=True).profile
    GameSnake.objects.create(game=game, snake=snake_factory.basic(profile=profile))
    GameSnake.objects.create(game=game, snake=snake_factory.basic(profile=profile))
    response = client.get("/")
    assert response.status_code == 200
    assert url in response.content.decode("utf-8")

play/apps/core/views/profile.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import render, redirect

from apps.core.models import Profile
from apps.core.forms import ProfileForm
from apps.core.middleware import profile_required


@login_required
def edit(request):
    profile, is_new_profile = Profile.objects.get_or_init(user=request.user)
    form = ProfileForm(instance=profile)
    return render(
        request,
        "core/profile/edit.html",
        {"form": form, "profile": profile, "show_activation": is_new_profile},
    )


@login_required
def update(request):
    profile, is_new_profile = Profile.objects.get_or_init(user=request.user)
    form = ProfileForm(request.POST, instance=profile)
    if form.is_valid():
        form.save()
        messages.add_message(request, messages.INFO, "Account settings updated")
        return redirect("u", profile.username)
    return render(
        request,
        "core/profile/edit.html",
        {"form": form, "profile": profile, "show_activation": is_new_profile},
        status=400,
    )


@login_required
@profile_required
@transaction.atomic
def delete(request):
    user = request.user
    logout(request)
    user.delete()
    if hasattr(user, "profile"):
        user.profile.delete()
    return redirect("/")

play/apps/core/views/profile_test.py
from apps.core.models import Profile
from apps.authentication.factories import UserFactory

user_factory = UserFactory()


def test_edit(client):
    user_factory.login_as(client)
    response = client.get("/settings/")
    assert response.status_code == 200


def test_update(client):
    user = user_factory.login_as(client)
    response = client.post("/settings/", {"email": "my-new-email", "_method": "PUT"})
    assert response.status_code == 302
    assert Profile.objects.get(user=user).email == "my-new-email"


def test_update_no_email(client):
    user_factory.login_as(client)
    response = client.post("/settings/", {"email": "", "_method": "PUT"})
    assert response.status_code == 400


def test_delete(client):
    user_factory.login_as(client)
    response = client.delete("/settings/")
    assert response.status_code == 302


def test_delete_no_profile(client):
    user_factory.login_as(client)
    response = client.delete("/settings/")
    assert response.status_code == 302

play/apps/core/templates/core/game/new.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-12 col-lg-7">
      <div class="form-group card">
        <h5 class="card-header">Create a Game</h5>
        <div class="card-body">
          <form method="post" novalidate action="">
            <h5 class="text-primary m-b-20 m-t-10">1. Select a Board Size</h5>
            {% csrf_token %}
            {% include "partials/forms/hidden_fields.html" with form=form %}
            {% include "partials/forms/field.html" with field=form.board_size label="Board Size" %}
            <div class="row">
              <div class="col">
                {% include "partials/forms/field.html" with field=form.width label="Width" %}
              </div>
              <div class="col">
                {% include "partials/forms/field.html" with field=form.height label="Height" %}
              </div>
            </div>
            {% include "partials/forms/field.html" with field=form.engine_url label="Engine URL" %}
            <h5 class="text-primary m-b-20 m-t-20">2. Add Snakes to the Pit</h5>
            <div id="snakes-alert" class="alert alert-danger alert-outline alert-dismissible fade hide" role="alert">
              Can't add more than 8 snakes to a game
            </div>
            <div class="form-group">
              <label>Find a Snake</label>
              <div class="row">
                <div class="col">
                  <select type="text"
                    id="snakes-list"
                    placeholder="type to search for snakes..."
                    class="form-control"
                    autocomplete="off"
                  data-url="/g/snake-autocomplete/"></select>
                </div>
                <div class="col-lg-2 py-2 px-lg-2 py-lg-0">
                  <button type="button"
                  id="add-snake-button"
                  class="btn btn-sm btn-primary btn-block">
                  Add
                  </button>
                </div>
              </div>
            </div>
            <div class="form-group">
              <label>Don't know any snakes?</label>
              <div class="row">
                <div class="col-lg-4 py-2 px-lg-3 py-lg-0">
                  <button type="button"
                  id="add-random-snake-button"
                  class="btn btn-sm btn-info btn-block">
                  Add a Random Snake
                  </button>
                </div>
              </div>
            </div>
            <div class="text-center">
              <button type="submit" class="m-t-20 btn btn-primary">Create Game</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-5">
      <div class="card">
        <h5 class="card-header text-primary">Snake Pit</h5>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-borderless">
              <th id="pit-empty-msg">No snakes added yet!</th>
              <tbody id="snake-table">
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block js_dom_ready %}

var $hiddenSnakesField = $('#id_snakes')
var $snakesAlert = $('#snakes-alert')
var MAX_SNAKES = 8

$('#snakes-list').autoComplete()
$('#snakes-list').keypress(function (e) {
  var code = (e.keyCode ? e.keyCode : e.which);
  if (code == 13) { // Enter key code
    addSnakeToForm()
    return false
  }
})

$(document).on('click', '#add-random-snake-button', function() {
  $.ajax({
    url: '/g/random-public-snake/?count=1'
  }).done(function(data) {
    $.each(data["snakes"], function(_, id) {
      updateHiddenSnakeIds(id)
    })
    updateSnakesTable()
  })
})

$(document).on('click', '#add-snake-button', function () {
  addSnakeToForm()
})

function getHiddenSnakeIds() {
  var snakes = $hiddenSnakesField.val()
  var s = []

  if (snakes.length > 0) {
    s = snakes.split(',')
  }
  return s
}

function updateHiddenSnakeIds(snakeId) {
  var existingSnakes = getHiddenSnakeIds()
  // Don't allow more than 8 snakes in the snakes list
  if (existingSnakes.length >= MAX_SNAKES) {
    $snakesAlert.addClass('show')
    $snakesAlert.removeClass('hide')
    setTimeout(function() {
      $snakesAlert.addClass('hide')
      $snakesAlert.removeClass('show')
    }, 2000)
    return
  }
  var current = $hiddenSnakesField.val()
  var fieldValue = !current ? snakeId : current + ',' + snakeId
  $hiddenSnakesField.val(fieldValue)
  updateSnakesTable()
}

function addSnakeToForm() {
  var snakeId = $('#snakes-list').next().next().val()
  if (!snakeId) {
    return
  }

  updateHiddenSnakeIds(snakeId)

  // This could be triggered by an enter keypress, if so, we need to delay a tad so
  // the autocomplete code can set the textbox
  setTimeout(function() {
    $('#snakes-list').val('').next().next().val('')
  }, 250)
}

function updateSnakesTable() {
  var snakes = getHiddenSnakeIds()
  // hide empty state message when there are snakes
  if (snakes.length > 0) {
    $('#pit-empty-msg').hide() 
  }
  // Don't allow more than 8 snakes in the snakes table
  if (snakes.length > MAX_SNAKES) {
    return
  }
  
  var table = $('#snake-table')   
  $.ajax({
    url: '/g/snake-info/?snakes=' + snakes.toString(),
  }).done(function (data) {
    table.empty()
    $.each(snakes, function (_, snakeId) {
      $.each(data, function (_, item) {
        if (item.value != snakeId) {
          return
        }
        table.append(
          '<tr>' +
            '<td>' + item.text + '</td>' +
            '<td class="text-right">' +
              '<button type="button" ' +
              'class="btn btn-danger btn-sm remove-snake" data-snake-id=' + item.value + '>' +
                '<strong>'+
                  '—' +
                '</strong>'+                
              '</button>' +
            '</td>' +
          '</tr>'
        )
      })
    })
  })
}

$(document).on('click', '.remove-snake', function () {
  var snakeIdToRemove = $(this).data('snake-id')
  var snakeIds = $hiddenSnakesField.val().split(',')
  var snakeIdIndex = snakeIds.indexOf(snakeIdToRemove)
  snakeIds.splice(snakeIdIndex, 1)
  $hiddenSnakesField.val(snakeIds)
  updateSnakesTable()
})

$('#id_height').parent().hide()
$('#id_width').parent().hide()
if (window.location.href.search("[?&]engine_url=") == -1) {
  $('#id_engine_url').parent().hide()
}

function changeSizeInputs(disabled) {
  var $height = $('#id_height')
  var $width = $('#id_width')
  if (disabled === true) {
    $height.parent().hide()
    $width.parent().hide()
  } else {
    $height.parent().show()
    $width.parent().show()
  }
  $width.prop('disabled', disabled)
  $height.prop('disabled', disabled)
}

$(document).on('change', '', function (event) {
  let size = $('#id_board_size').val()
  if (size === 'custom') {
    changeSizeInputs(false)
  } else {
    changeSizeInputs(true)
  }
})

updateSnakesTable()
{% endblock %}

play/apps/core/templates/core/game/show.html
{% extends "base.html" %}

{% block content %}
<div class="card">
  <div class="embed-responsive embed-responsive-1by1" style="max-height: 800px;">
    <iframe
      id="iframe_game"
      src="{{ url | safe }}"
      scrolling="no"
      class="embed-responsive-item p-lg-3">
    </iframe>
  </div>

  <div class="card-body">
    <div class="row">
      <div class="col d-flex justify-content-center">
        <a href="#"
          class="btn btn-info btn-outline mr-2 d-none js-share-game-at-turn">
          Share this game
        </a>
        <a href="{% url 'game_gif' engine_id=game.engine_id %}"
          class="btn btn-info btn-outline">
          View as GIF
        </a>
      </div>
    </div>
  </div>

  <div class="card-footer text-center d-none d-sm-block" style="height: 150px;">
    <h3 id="js-snake-highlighted-name"></h3>
    <a id="js-snake-highlighted-link" href="#"
      class="btn btn-info btn-outline d-none">
      View Profile
    </a>
  </div>
</div>
{% endblock %}

{% block js_dom_ready %}
var shareButtonClass = '.js-share-game-at-turn'
var gameIframeId = 'iframe_game'
var pageUrlWithoutQuerystring = window.location.origin + window.location.pathname
var turnCount = 0
var clipboard = new ClipboardJS(shareButtonClass)
var $shareButton = $(shareButtonClass)
var $gameIframe = $('#' + gameIframeId)
var snakeName = $('#js-snake-highlighted-name')
var snakeLink = $('#js-snake-highlighted-link')

var acceptedKeyCodes = [
  'left',
  'right',
  'space',
  'r',
]

var isSmallScreen = $(window).width() < 992 // Bootstrap `md` breakpoint

// Set the initial share button text to copy
$shareButton.attr('data-clipboard-text', pageUrlWithoutQuerystring)

clipboard.on('success', function (event) {
  if (turnCount === 0) {
    __battlesnake.setTooltip(
      event.trigger,
      'Copied shareable URL to your clipboard!'
    )
  } else {
    __battlesnake.setTooltip(
      event.trigger,
      'Copied shareable URL at turn ' + turnCount + ' to your clipboard!'
    )
  }
  __battlesnake.hideTooltip()
})

$shareButton.on('click', function (e) {
  e.preventDefault()
})

// Capture and forward keyboard events to the Board iframe
var gameIframe = document.getElementById(gameIframeId)
Mousetrap.bind(acceptedKeyCodes, function(e) {
  e.preventDefault();
  if (gameIframe) {
    gameIframe.contentWindow.postMessage({
      code: e.code,
      keyCode: e.keyCode // DEPRECATED: Remove after next Board deploy
    }, __battlesnake.settings.BOARD_URL)
  }
})

window.addEventListener('message', function (e) {
  if (e.origin !== __battlesnake.settings.BOARD_URL) {
    return;
  }

  var msg = e.data;

  if (msg.action === 'SET_CURRENT_FRAME') {
    if (!isSmallScreen) {
      turnCount = msg.frame.turn
      $shareButton.attr('data-clipboard-text', pageUrlWithoutQuerystring + '?turn=' + turnCount)
    }
  }

  if (msg.action === 'HIGHLIGHT_SNAKE') {
    if (msg.id) {
      snakeName.text(msg.name);
      snakeLink.attr('href', '/u/by-games-snake/' + msg.id);
      snakeLink.removeClass('d-none');
    } else {
      snakeName.text('');
      snakeLink.addClass('d-none');
    }
  }
}, false)


$gameIframe.on('load', function () {
  // Use Bootstrap breakpoint
  if (isSmallScreen) {
    var iframeSrc = $(this).attr('src')
    // If we're in a narrow view where the media controls don't display,
    // simply autoplay the game
    if (!~iframeSrc.indexOf('autoplay')) {
      $(this).attr('src', iframeSrc + '&autoplay=true')
    }
  }

  $shareButton.removeClass('d-none')
})
{% endblock %}